name: Trigger Test

on:
  push:

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - run: |
          pwd
          ls -al
          python3 --version
          python3 ${GITHUB_WORKSPACE}/test.py
